### ISSUE TITLE
Client names for wireless strength/speed

### ISSUE THREAD

**Issue by agneevX** [DRuggeri/netgear_exporter#8]
I'm not sure how to create a Grafana chart showing client names next to their respective wireless speed/strength, because it's not present in `netgear_client_wireless_speed` or `netgear_client_wireless_strength` but present in `netgear_client_info`.

Can you help me here? Thanks.

**Comment by DRuggeri** [comment]
Hey there, @agneevX  - really sorry for the slow response. I think you would need to use Prometheus's built-in metric joining operators. Here's a handy tutorial I've used in the past:

https://ypereirareis.github.io/blog/2020/02/21/how-to-join-prometheus-metrics-by-label-with-promql/

One thing to note: on my own install, I had to disable the `clients` collector because my RBR50 was simply not up to the task... when I ran a scrape, it would pause traffic while it gathered the metrics!
